# Generated by Django 2.2.24 on 2024-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0013_auto_20200115_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemode',
            name='strike_price',
            field=models.IntegerField(default=0, verbose_name='Strike Price(%)'),
        ),
        migrations.AddField(
            model_name='historicalcoursemode',
            name='strike_price',
            field=models.IntegerField(default=0, verbose_name='Strike Price(%)'),
        ),
        migrations.AlterField(
            model_name='coursemode',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AlterField(
            model_name='coursemode',
            name='sku',
            field=models.CharField(blank=True, help_text='OPTIONAL: This is the SKU (stock keeping unit) of this mode in the external ecommerce service.  Leave this blank if the course has not yet been migrated to the ecommerce service.', max_length=255, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='coursemodesarchive',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='sku',
            field=models.CharField(blank=True, help_text='OPTIONAL: This is the SKU (stock keeping unit) of this mode in the external ecommerce service.  Leave this blank if the course has not yet been migrated to the ecommerce service.', max_length=255, null=True, verbose_name='Product ID'),
        ),
    ]
