# Generated by Django 2.2.24 on 2022-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0015_auto_20220103_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='strike_price',
            field=models.IntegerField(default=0, verbose_name='Strike Price(%)'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='strike_price',
            field=models.IntegerField(default=0, verbose_name='Strike Price(%)'),
        ),
    ]
