# Generated by Django 2.2.24 on 2024-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0016_auto_20220129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='sku',
            field=models.CharField(blank=True, help_text="Enter the Paddle product ID here to retrieve the currency and price based on the user's location.", max_length=255, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='sku',
            field=models.CharField(blank=True, help_text="Enter the Paddle product ID here to retrieve the currency and price based on the user's location.", max_length=255, null=True, verbose_name='Product ID'),
        ),
    ]
