# Generated by Django 4.2.17 on 2025-03-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_modes", "0015_auto_20241211_0614"),
        ("course_modes", "0016_alter_historicalcoursemode_options"),
    ]

    operations = []
