# Generated by Django 4.2.17 on 2025-03-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_modes", "0016_alter_historicalcoursemode_options"),
        ("course_modes", "0017_auto_20241218_2056"),
    ]

    operations = []
