# Generated by Django 4.2.17 on 2025-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_modes", "0017_merge_20250317_1830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodesarchive",
            name="currency",
            field=models.CharField(default="usd", max_length=8),
        ),
    ]
