# Generated by Django 4.2.17 on 2025-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_modes", "0018_merge_20250318_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemode",
            name="min_price_usd",
            field=models.IntegerField(default=0, verbose_name="Price in USD"),
        ),
        migrations.AddField(
            model_name="historicalcoursemode",
            name="min_price_usd",
            field=models.IntegerField(default=0, verbose_name="Price in USD"),
        ),
        migrations.AlterField(
            model_name="coursemode",
            name="min_price",
            field=models.IntegerField(default=0, verbose_name="Price in INR"),
        ),
        migrations.AlterField(
            model_name="coursemodesarchive",
            name="currency",
            field=models.CharField(default="usd", max_length=8),
        ),
        migrations.AlterField(
            model_name="historicalcoursemode",
            name="min_price",
            field=models.IntegerField(default=0, verbose_name="Price in INR"),
        ),
    ]
