# Generated by Django 4.2.17 on 2025-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_modes", "0018_merge_20250318_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodesarchive",
            name="currency",
            field=models.CharField(default="usd", max_length=8),
        ),
    ]
