# Generated by Django 2.2.24 on 2022-10-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_add_mode_20201118_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcertificate',
            name='download_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgeneratedcertificate',
            name='download_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
