# Generated by Django 2.2.24 on 2022-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_auto_20221012_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='share_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicalgeneratedcertificate',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicalgeneratedcertificate',
            name='share_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
