# Generated by Django 4.2.17 on 2025-03-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0019_auto_20221015_0837"),
        ("certificates", "0037_fix_legacy_broken_invalid_certs"),
    ]

    operations = []
