# Generated by Django 4.2.17 on 2025-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0038_merge_20250318_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcertificate",
            name="download_url",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="historicalgeneratedcertificate",
            name="download_url",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
