# Generated by Django 2.2.24 on 2024-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20201021_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_entity',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_business_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
