# Generated by Django 2.2.24 on 2022-11-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20201021_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_business_account',
            field=models.BooleanField(default=False),
        ),
    ]
