# Generated by Django 2.2.24 on 2022-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_userprofile_is_business_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_entity',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
