# Generated by Django 2.2.24 on 2024-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20240713_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
