# Generated by Django 4.2.17 on 2025-03-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0040_userprofile_postal_code"),
        ("student", "0046_alter_userprofile_phone_number"),
    ]

    operations = []
