# Generated by Django 4.2.17 on 2025-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0047_merge_20250318_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mailing_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
